#!/bin/sh
#
# Set up MinIO.

set -eux

echo 'PASSWORD: '$PASSWORD
pkg install www/minio
sysrc minio_root_user=server
sysrc minio_root_password=$PASSWORD
sysrc minio_enable=YES
service minio start
